create database AlohaTraining2
go
use AlohaTraining2
go

create table State
(
Id Int not null identity(1,1) Primary Key,
Code Char(2),
Name  varchar(100)
)
go
create table City
(
Id Int not null identity(1,1) Primary Key,
Code Char(3),
Name  varchar(100),
StateId int not null foreign key references State(Id)
)
go
create table Area
(
Id Int not null identity(1,1) Primary Key,
Code Char(3),
Name  varchar(100),
CityId int not null foreign key references City(Id)
)
go
create table Gender
(
Id Int not null identity(1,1) Primary Key,
Code Char(2),
Name  varchar(100),
)
go
create table Type
(
Id Int not null identity(1,1) Primary Key,
Code Char(3),
Name  varchar(100)
)
go
create table Branch
(
Id Int not null identity(1,1) Primary Key,
Code varchar(10),
Name  varchar(100)
)
go
create table Department
(
Id Int not null identity(1,1) Primary Key,
Code varchar(10),
Name  varchar(100)
)

insert into Gender values ('','Male'),('','Female'),('','Others')

insert into Type values ('','Permanent'),('','Contract')

insert into Branch values ('','ECE'),('','CSE'),('','IT')

insert into Department values ('','IT'),('','HR'),('','Marketing')


select * from Department


INSERT INTO state VALUES
('AP','ANDHRA PRADESH'),
('AS','ASSAM'),
('AR','ARUNACHAL PRADESH'),
('BR','BIHAR'),
('GJ','GUJRAT'),
('HR','HARYANA'),
('HP','HIMACHAL PRADESH'),
('JK','JAMMU & KASHMIR'),
('KA','KARNATAKA'),
('KL','KERALA'),
('MP','MADHYA PRADESH'),
('MH','MAHARASHTRA'),
('MN','MANIPUR'),
('ML','MEGHALAYA'),
('MZ','MIZORAM'),
('NL','NAGALAND'),
('OR','ORISSA'),
('PB','PUNJAB'),
('RJ','RAJASTHAN'),
('SK','SIKKIM'),
('TN','TAMIL NADU'),
('TR','TRIPURA'),
('UK','UTTARANCHAL'),
('UP','UTTAR PRADESH'),
('WB','WEST BENGAL'),
('DL','DELHI'),
('GA','GOA'),
('PY','PONDICHERY'),
('LD','LAKSHDWEEP'),
('DD','DAMAN & DIU'),
('DH','DADRA & NAGAR'),
('CH','CHANDIGARH'),
('AN','ANDAMAN & NICOBAR'),
('JH','JHARKHAND'),
('CG','CHATTISGARH');




INSERT INTO city  VALUES
('','North and Middle Andaman', 32),
('','South Andaman', 32),
('','Nicobar', 32),
('','Adilabad', 1),
('','Anantapur', 1),
('','Chittoor', 1),
('','East Godavari', 1),
('','Guntur', 1),
('','Hyderabad', 1),
('','Kadapa', 1),
('','Karimnagar', 1),
('','Khammam', 1),
('','Krishna', 1),
('','Kurnool', 1),
('','Mahbubnagar', 1),
('','Medak', 1),
('','Nalgonda', 1),
('','Nellore', 1),
('','Nizamabad', 1),
('','Prakasam', 1),
('','Rangareddi', 1),
('','Srikakulam', 1),
('','Vishakhapatnam', 1),
('','Vizianagaram', 1),
('','Warangal', 1),
('','West Godavari', 1),
('','Anjaw', 3),
('','Changlang', 3),
('','East Kameng', 3),
('','Lohit', 3),
('','Lower Subansiri', 3),
('','Papum Pare', 3),
('','Tirap', 3),
('','Dibang Valley', 3),
('','Upper Subansiri', 3),
('','West Kameng', 3),
('','Barpeta', 2),
('','Bongaigaon', 2),
('','Cachar', 2),
('','Darrang', 2),
('','Dhemaji', 2),
('','Dhubri', 2),
('','Dibrugarh', 2),
('','Goalpara', 2),
('','Golaghat', 2),
('','Hailakandi', 2),
('','Jorhat', 2),
('','Karbi Anglong', 2),
('','Karimganj', 2),
('','Kokrajhar', 2),
('','Lakhimpur', 2),
('','Marigaon', 2),
('','Nagaon', 2),
('','Nalbari', 2),
('','North Cachar Hills', 2),
('','Sibsagar', 2),
('','Sonitpur', 2),
('','Tinsukia', 2),
('','Araria', 4),
('','Aurangabad', 4),
('','Banka', 4),
('','Begusarai', 4),
('','Bhagalpur', 4),
('','Bhojpur', 4),
('','Buxar', 4),
('','Darbhanga', 4),
('','Purba Champaran', 4),
('','Gaya', 4),
('','Gopalganj', 4),
('','Jamui', 4),
('','Jehanabad', 4),
('','Khagaria', 4),
('','Kishanganj', 4),
('','Kaimur', 4),
('','Katihar', 4),
('','Lakhisarai', 4),
('','Madhubani', 4),
('','Munger', 4),
('','Madhepura', 4),
('','Muzaffarpur', 4),
('','Nalanda', 4),
('','Nawada', 4),
('','Patna', 4),
('','Purnia', 4),
('','Rohtas', 4),
('','Saharsa', 4),
('','Samastipur', 4),
('','Sheohar', 4),
('','Sheikhpura', 4),
('','Saran', 4),
('','Sitamarhi', 4),
('','Supaul', 4),
('','Siwan', 4),
('','Vaishali', 4),
('','Pashchim Champaran', 4),
('','Diu', 29),
('','Daman', 29),
('','Central Delhi', 25),
('','East Delhi', 25),
('','New Delhi', 25),
('','North Delhi', 25),
('','North East Delhi', 25),
('','North West Delhi', 25),
('','South Delhi', 25),
('','South West Delhi', 25),
('','West Delhi', 25),
('','North Goa', 26),
('','South Goa', 26),
('','Ahmedabad', 5),
('','Amreli District', 5),
('','Anand', 5),
('','Banaskantha', 5),
('','Bharuch', 5),
('','Bhavnagar', 5),
('','Dahod', 5),
('','The Dangs', 5),
('','Gandhinagar', 5),
('','Jamnagar', 5),
('','Junagadh', 5),
('','Kutch', 5),
('','Kheda', 5),
('','Mehsana', 5),
('','Narmada', 5),
('','Navsari', 5),
('','Patan', 5),
('','Panchmahal', 5),
('','Porbandar', 5),
('','Rajkot', 5),
('','Sabarkantha', 5),
('','Surendranagar', 5),
('','Surat', 5),
('','Vadodara', 5),
('','Valsad', 5),
('','Ambala', 6),
('','Bhiwani', 6),
('','Faridabad', 6),
('','Fatehabad', 6),
('','Gurgaon', 6),
('','Hissar', 6),
('','Jhajjar', 6),
('','Jind', 6),
('','Karnal', 6),
('','Kaithal', 6),
('','Kurukshetra', 6),
('','Mahendragarh', 6),
('','Mewat', 6),
('','Panchkula', 6),
('','Panipat', 6),
('','Rewari', 6),
('','Rohtak', 6),
('','Sirsa', 6),
('','Sonepat', 6),
('','Yamuna Nagar', 6),
('','Palwal', 6),
('','Bilaspur', 7),
('','Chamba', 7),
('','Hamirpur', 7),
('','Kangra', 7),
('','Kinnaur', 7),
('','Kulu', 7),
('','Lahaul and Spiti', 7),
('','Mandi', 7),
('','Shimla', 7),
('','Sirmaur', 7),
('','Solan', 7),
('','Una', 7),
('','Anantnag', 8),
('','Badgam', 8),
('','Bandipore', 8),
('','Baramula', 8),
('','Doda', 8),
('','Jammu', 8),
('','Kargil', 8),
('','Kathua', 8),
('','Kupwara', 8),
('','Leh', 8),
('','Poonch', 8),
('','Pulwama', 8),
('','Rajauri', 8),
('','Srinagar', 8),
('','Samba', 8),
('','Udhampur', 8),
('','Bokaro', 34),
('','Chatra', 34),
('','Deoghar', 34),
('','Dhanbad', 34),
('','Dumka', 34),
('','Purba Singhbhum', 34),
('','Garhwa', 34),
('','Giridih', 34),
('','Godda', 34),
('','Gumla', 34),
('','Hazaribagh', 34),
('','Koderma', 34),
('','Lohardaga', 34),
('','Pakur', 34),
('','Palamu', 34),
('','Ranchi', 34),
('','Sahibganj', 34),
('','Seraikela and Kharsawan', 34),
('','Pashchim Singhbhum', 34),
('','Ramgarh', 34),
('','Bidar', 9),
('','Belgaum', 9),
('','Bijapur', 9),
('','Bagalkot', 9),
('','Bellary', 9),
('','Bangalore Rural District', 9),
('','Bangalore Urban District', 9),
('','Chamarajnagar', 9),
('','Chikmagalur', 9),
('','Chitradurga', 9),
('','Davanagere', 9),
('','Dharwad', 9),
('','Dakshina Kannada', 9),
('','Gadag', 9),
('','Gulbarga', 9),
('','Hassan', 9),
('','Haveri District', 9),
('','Kodagu', 9),
('','Kolar', 9),
('','Koppal', 9),
('','Mandya', 9),
('','Mysore', 9),
('','Raichur', 9),
('','Shimoga', 9),
('','Tumkur', 9),
('','Udupi', 9),
('','Uttara Kannada', 9),
('','Ramanagara', 9),
('','Chikballapur', 9),
('','Yadagiri', 9),
('','Alappuzha', 10),
('','Ernakulam', 10),
('','Idukki', 10),
('','Kollam', 10),
('','Kannur', 10),
('','Kasaragod', 10),
('','Kottayam', 10),
('','Kozhikode', 10),
('','Malappuram', 10),
('','Palakkad', 10),
('','Pathanamthitta', 10),
('','Thrissur', 10),
('','Thiruvananthapuram', 10),
('','Wayanad', 10),
('','Alirajpur', 11),
('','Anuppur', 11),
('','Ashok Nagar', 11),
('','Balaghat', 11),
('','Barwani', 11),
('','Betul', 11),
('','Bhind', 11),
('','Bhopal', 11),
('','Burhanpur', 11),
('','Chhatarpur', 11),
('','Chhindwara', 11),
('','Damoh', 11),
('','Datia', 11),
('','Dewas', 11),
('','Dhar', 11),
('','Dindori', 11),
('','Guna', 11),
('','Gwalior', 11),
('','Harda', 11),
('','Hoshangabad', 11),
('','Indore', 11),
('','Jabalpur', 11),
('','Jhabua', 11),
('','Katni', 11),
('','Khandwa', 11),
('','Khargone', 11),
('','Mandla', 11),
('','Mandsaur', 11),
('','Morena', 11),
('','Narsinghpur', 11),
('','Neemuch', 11),
('','Panna', 11),
('','Rewa', 11),
('','Rajgarh', 11),
('','Ratlam', 11),
('','Raisen', 11),
('','Sagar', 11),
('','Satna', 11),
('','Sehore', 11),
('','Seoni', 11),
('','Shahdol', 11),
('','Shajapur', 11),
('','Sheopur', 11),
('','Shivpuri', 11),
('','Sidhi', 11),
('','Singrauli', 11),
('','Tikamgarh', 11),
('','Ujjain', 11),
('','Umaria', 11),
('','Vidisha', 11),
('','Ahmednagar', 12),
('','Akola', 12),
('','Amrawati', 12),
('','Aurangabad', 12),
('','Bhandara', 12),
('','Beed', 12),
('','Buldhana', 12),
('','Chandrapur', 12),
('','Dhule', 12),
('','Gadchiroli', 12),
('','Gondiya', 12),
('','Hingoli', 12),
('','Jalgaon', 12),
('','Jalna', 12),
('','Kolhapur', 12),
('','Latur', 12),
('','Mumbai City', 12),
('','Mumbai suburban', 12),
('','Nandurbar', 12),
('','Nanded', 12),
('','Nagpur', 12),
('','Nashik', 12),
('','Osmanabad', 12),
('','Parbhani', 12),
('','Pune', 12),
('','Raigad', 12),
('','Ratnagiri', 12),
('','Sindhudurg', 12),
('','Sangli', 12),
('','Solapur', 12),
('','Satara', 12),
('','Thane', 12),
('','Wardha', 12),
('','Washim', 12),
('','Yavatmal', 12),
('','Bishnupur', 13),
('','Churachandpur', 13),
('','Chandel', 13),
('','Imphal East', 13),
('','Senapati', 13),
('','Tamenglong', 13),
('','Thoubal', 13),
('','Ukhrul', 13),
('','Imphal West', 13),
('','East Garo Hills', 14),
('','East Khasi Hills', 14),
('','Jaintia Hills', 14),
('','Ri-Bhoi', 14),
('','South Garo Hills', 14),
('','West Garo Hills', 14),
('','West Khasi Hills', 14),
('','Aizawl', 15),
('','Champhai', 15),
('','Kolasib', 15),
('','Lawngtlai', 15),
('','Lunglei', 15),
('','Mamit', 15),
('','Saiha', 15),
('','Serchhip', 15),
('','Dimapur', 16),
('','Kohima', 16),
('','Mokokchung', 16),
('','Mon', 16),
('','Phek', 16),
('','Tuensang', 16),
('','Wokha', 16),
('','Zunheboto', 16),
('','Angul', 17),
('','Boudh', 17),
('','Bhadrak', 17),
('','Bolangir', 17),
('','Bargarh', 17),
('','Baleswar', 17),
('','Cuttack', 17),
('','Debagarh', 17),
('','Dhenkanal', 17),
('','Ganjam', 17),
('','Gajapati', 17),
('','Jharsuguda', 17),
('','Jajapur', 17),
('','Jagatsinghpur', 17),
('','Khordha', 17),
('','Kendujhar', 17),
('','Kalahandi', 17),
('','Kandhamal', 17),
('','Koraput', 17),
('','Kendrapara', 17),
('','Malkangiri', 17),
('','Mayurbhanj', 17),
('','Nabarangpur', 17),
('','Nuapada', 17),
('','Nayagarh', 17),
('','Puri', 17),
('','Rayagada', 17),
('','Sambalpur', 17),
('','Subarnapur', 17),
('','Sundargarh', 17),
('','Karaikal', 27),
('','Mahe', 27),
('','Puducherry', 27),
('','Yanam', 27),
('','Amritsar', 18),
('','Bathinda', 18),
('','Firozpur', 18),
('','Faridkot', 18),
('','Fatehgarh Sahib', 18),
('','Gurdaspur', 18),
('','Hoshiarpur', 18),
('','Jalandhar', 18),
('','Kapurthala', 18),
('','Ludhiana', 18),
('','Mansa', 18),
('','Moga', 18),
('','Mukatsar', 18),
('','Nawan Shehar', 18),
('','Patiala', 18),
('','Rupnagar', 18),
('','Sangrur', 18),
('','Ajmer', 19),
('','Alwar', 19),
('','Bikaner', 19),
('','Barmer', 19),
('','Banswara', 19),
('','Bharatpur', 19),
('','Baran', 19),
('','Bundi', 19),
('','Bhilwara', 19),
('','Churu', 19),
('','Chittorgarh', 19),
('','Dausa', 19),
('','Dholpur', 19),
('','Dungapur', 19),
('','Ganganagar', 19),
('','Hanumangarh', 19),
('','Juhnjhunun', 19),
('','Jalore', 19),
('','Jodhpur', 19),
('','Jaipur', 19),
('','Jaisalmer', 19),
('','Jhalawar', 19),
('','Karauli', 19),
('','Kota', 19),
('','Nagaur', 19),
('','Pali', 19),
('','Pratapgarh', 19),
('','Rajsamand', 19),
('','Sikar', 19),
('','Sawai Madhopur', 19),
('','Sirohi', 19),
('','Tonk', 19),
('','Udaipur', 19),
('','East Sikkim', 20),
('','North Sikkim', 20),
('','South Sikkim', 20),
('','West Sikkim', 20),
('','Ariyalur', 21),
('','Chennai', 21),
('','Coimbatore', 21),
('','Cuddalore', 21),
('','Dharmapuri', 21),
('','Dindigul', 21),
('','Erode', 21),
('','Kanchipuram', 21),
('','Kanyakumari', 21),
('','Karur', 21),
('','Madurai', 21),
('','Nagapattinam', 21),
('','The Nilgiris', 21),
('','Namakkal', 21),
('','Perambalur', 21),
('','Pudukkottai', 21),
('','Ramanathapuram', 21),
('','Salem', 21),
('','Sivagangai', 21),
('','Tiruppur', 21),
('','Tiruchirappalli', 21),
('','Theni', 21),
('','Tirunelveli', 21),
('','Thanjavur', 21),
('','Thoothukudi', 21),
('','Thiruvallur', 21),
('','Thiruvarur', 21),
('','Tiruvannamalai', 21),
('','Vellore', 21),
('','Villupuram', 21),
('','Dhalai', 22),
('','North Tripura', 22),
('','South Tripura', 22),
('','West Tripura', 22),
('','Almora', 33),
('','Bageshwar', 33),
('','Chamoli', 33),
('','Champawat', 33),
('','Dehradun', 33),
('','Haridwar', 33),
('','Nainital', 33),
('','Pauri Garhwal', 33),
('','Pithoragharh', 33),
('','Rudraprayag', 33),
('','Tehri Garhwal', 33),
('','Udham Singh Nagar', 33),
('','Uttarkashi', 33),
('','Agra', 23),
('','Allahabad', 23),
('','Aligarh', 23),
('','Ambedkar Nagar', 23),
('','Auraiya', 23),
('','Azamgarh', 23),
('','Barabanki', 23),
('','Badaun', 23),
('','Bagpat', 23),
('','Bahraich', 23),
('','Bijnor', 23),
('','Ballia', 23),
('','Banda', 23),
('','Balrampur', 23),
('','Bareilly', 23),
('','Basti', 23),
('','Bulandshahr', 23),
('','Chandauli', 23),
('','Chitrakoot', 23),
('','Deoria', 23),
('','Etah', 23),
('','Kanshiram Nagar', 23),
('','Etawah', 23),
('','Firozabad', 23),
('','Farrukhabad', 23),
('','Fatehpur', 23),
('','Faizabad', 23),
('','Gautam Buddha Nagar', 23),
('','Gonda', 23),
('','Ghazipur', 23),
('','Gorkakhpur', 23),
('','Ghaziabad', 23),
('','Hamirpur', 23),
('','Hardoi', 23),
('','Mahamaya Nagar', 23),
('','Jhansi', 23),
('','Jalaun', 23),
('','Jyotiba Phule Nagar', 23),
('','Jaunpur District', 23),
('','Kanpur Dehat', 23),
('','Kannauj', 23),
('','Kanpur Nagar', 23),
('','Kaushambi', 23),
('','Kushinagar', 23),
('','Lalitpur', 23),
('','Lakhimpur Kheri', 23),
('','Lucknow', 23),
('','Mau', 23),
('','Meerut', 23),
('','Maharajganj', 23),
('','Mahoba', 23),
('','Mirzapur', 23),
('','Moradabad', 23),
('','Mainpuri', 23),
('','Mathura', 23),
('','Muzaffarnagar', 23),
('','Pilibhit', 23),
('','Pratapgarh', 23),
('','Rampur', 23),
('','Rae Bareli', 23),
('','Saharanpur', 23),
('','Sitapur', 23),
('','Shahjahanpur', 23),
('','Sant Kabir Nagar', 23),
('','Siddharthnagar', 23),
('','Sonbhadra', 23),
('','Sant Ravidas Nagar', 23),
('','Sultanpur', 23),
('','Shravasti', 23),
('','Unnao', 23),
('','Varanasi', 23),
('','Birbhum', 24),
('','Bankura', 24),
('','Bardhaman', 24),
('','Darjeeling', 24),
('','Dakshin Dinajpur', 24),
('','Hooghly', 24),
('','Howrah', 24),
('','Jalpaiguri', 24),
('','Cooch Behar', 24),
('','Kolkata', 24),
('','Malda', 24),
('','Midnapore', 24),
('','Murshidabad', 24),
('','Nadia', 24),
('','North 24 Parganas', 24),
('','South 24 Parganas', 24),
('','Purulia', 24),
('','Uttar Dinajpur', 24);

select * from state
select * from city where StateId = 5


INSERT INTO Area  VALUES
('','Manikonda',9),
('','Financial District',9),
('','Gachibowli',9),
('','Raidurg',9),
('','Khajaguda',9),
('','Manikonda',9),
('','Nanakramguda',9),
('','Kokapet',9),
('','Shaikpet Hyderabad',9),
('','HITEC City',9),
('','HITEC City',9),
('','Madhapur',9),
('','Kondapur',9),
('','Jubilee Hills',9),
('','Jubilee Hills',9),
('','Banjara Hills',9),
('','Film Nagar',9),
('','Yousufguda',9),
('','Srinagar colony',9),
('','North Western',9);



INSERT INTO Area  VALUES
('','Ahmedabad Locality Maps',109),
('','Ambawadi',109),
('','Amraiwadi',109),
('','Asarwa',109),
('','Ashram Road',109),
('','Aslali',109),
('','Astodia',109),
('','Bapunagar',109),
('','Bardolpura',109),
('','Behrampura',109),
('','Bhadra',109),
('','Bodakdev',109),
('','Bopal',109),
('','CG Road',109),
('','Chandkheda',109),
('','Chandlodia',109),
('','Changodar',109),
('','CTM',109),
('','CTM Char Rasta',109),
('','Dani Limbada',109),
('','Dariapur',109),
('','Delhi Chakla',109),
('','Delhi Darwaja',109),
('','Drive In Road',109),
('','Dudheshwar',109),
('','Dudheshwar Road',109),
('','Ellis Bridge',109),
('','Gandhi Road',109),
('','Geeta Mandir',109),
('','Geeta Mandir Road',109),
('','Ghatlodia',109),
('','Gheekanta',109),
('','Gheekanta Road',109),
('','Ghodasar',109),
('','Gomtipur',109),
('','Gota',109),
('','Gulbai Tekra',109),
('','Gurukul',109),
('','Hatkeshwar',109),
('','Income Tax',109),
('','Isanpur',109),
('','Jamalpur',109),
('','Jasodanagar',109),
('','Jivraj Park',109),
('','Jodhpur',109),
('','Juhapura',109),
('','Juna Wadaj',109),
('','Kalupur',109),
('','Kankaria',109),
('','Kankaria Road',109),
('','Kathwada',109),
('','Khadia',109),
('','Khamasa',109),
('','Khanpur',109),
('','Khokhara',109),
('','Krishnanagar',109),
('','Kuber Nagar',109),
('','Madhupura',109),
('','Manek Chowk',109),
('','Maninagar',109),
('','Meghani Nagar',109),
('','Memnagar',109),
('','Mirzapur',109),
('','Mirzapur Road',109),
('','Naranpura',109),
('','Naroda',109),
('','Naroda GIDC',109),
('','Naroda road',109),
('','Narol',109),
('','Nava Wadaj',109),
('','Navarangpura Gam',109),
('','Nikol',109),
('','Nirnay Nagar',109),
('','Odhav',109),
('','Odhav GIDC',109),
('','Odhav Road',109),
('','Paldi',109),
('','Pankore Naka',109),
('','Patharkuva',109),
('','Patthar Kuva',109),
('','Raipur',109),
('','Rakhial',109),
('','Ranip',109),
('','Ranna Park',109),
('','Ratan Pole',109),
('','Revdi Bazaar',109),
('','Sabarmati',109),
('','Sahijpur Bogha',109),
('','Sarangpur',109),
('','Saraspur',109),
('','Sardar Nagar',109),
('','Sarkej',109),
('','Sarkhej Gandhinagar Highway',109),
('','Satellite',109),
('','Satellite Road',109),
('','Shah Alam Road',109),
('','Shahibagh',109),
('','Shahibaug Road',109),
('','Shahpur',109),
('','Sola',109),
('','Sola Road',109),
('','Subhash Bridge',109),
('','Tavdipura',109),
('','Teen Darwaja',109),
('','Thakkarbapa Nagar',109),
('','Thaltej',109),
('','Usmanpura',109),
('','Vasna',109),
('','Vastral',109),
('','Vastrapur',109),
('','Vatva',109),
('','Vatva GIDC',109),
('','Vejalpur',109)

select * from state
select * from city where stateid = 12

INSERT INTO Area  VALUES
('','Andheri - Kurla Road',313),
('','Andheri (E) - Marol',313),
('','Andheri (E) - MIDC',313),
('','Andheri (E) - Station',313),
('','Andheri (W)',313),
('','Ballard Estate',313),
('','Band Stand',313),
('','Bandra (E)',313),
('','Bandra (W)',313),
('','Bandra Kurla Complex',313),
('','Byculla',313),
('','Chembur',313),
('','Church Gate',313),
('','Colaba',313),
('','Cuffe Parade',313),
('','Dadar (Central)',313),
('','Dadar (West)',313),
('','Domestic Airport',313),
('','Gateway of India',313),
('','Goregaon (E)',313),
('','Goregaon (W)',313),
('','International Airport',313),
('','Juhu',313),
('','Kemps Corner',313),
('','Khar (W)',313),
('','Kurla (W)',313),
('','Linking Road',313),
('','Malad (W)',313),
('','Marine Drive',313),
('','Mulund (W)',313),
('','Mumbai CST',313),
('','Nariman Point',313),
('','New Marine Lines',313),
('','Pali Hill',313),
('','Parel',313),
('','Powai',313),
('','Saki Naka',313),
('','Santacruz (E)',313),
('','Shivaji Park',313),
('','Tardeo',313),
('','Ville Parle (E)',313),
('','Worli',313)



--select * from city where name like '%k%'

--select * from state s join city c on s.Id = c.StateId  where c.Name like '%Tiruchirappalli%'
